myproject/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path('__debug__/', include(debug_toolbar.urls)),

    path('characters/', include('characters.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('', views.home_view, name='home'),
    # path('dupa/', views.dupa_view, name='dupa'),
    path('register/', views.register_view, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('change_password/', views.change_password_view, name='change-password'),
    # path('edit-profile/', views.edit_profile_view, name='edit-profile'),
    path('edit-user/', views.edit_user_view, name='edit-user'),
    # path('switch-profile:<int:profile_id>/', views.switch_profile, name='switch-profile'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models import PROTECT, BooleanField, CharField, OneToOneField
from django.db.models.functions import Collate

from resources.models import Picture


class User(AbstractUser):
    picture = OneToOneField(Picture, on_delete=PROTECT, blank=True, null=True)
    collation = CharField(max_length=30, blank=True, null=True)
    is_spectator = BooleanField(default=False)   # Indicates if user can view site content but without editing it

    class Meta:
        ordering = [Collate('username', 'pl-PL-x-icu')]

    @property
    def is_gamemaster(self):
        return all([self.is_staff, self.is_superuser])

    @property
    def is_auxiliary(self):
        """Potentially for game masters missing full admin permissions?"""
        return self.is_staff and not self.is_superuser

    @property
    def is_player(self):
        return not any([self.is_staff, self.is_superuser, self.is_spectator])

    @property
    def is_active_player(self):
        return all([self.is_player, self.is_active])

    @property
    def can_action(self):
        return self.is_active and not self.is_spectator

    @property
    def can_view_all(self):
        return any([self.is_superuser, self.is_staff, self.is_spectator])

    @property
    def picture_url(self):
        try:
            return self.picture.image.url
        except ValueError:
            return settings.STATIC_URL + "users/default.jpg"


#     @property
#     def undone_demands(self):
#         demands = self.received_demands.exclude(author=self)
#         return demands.exclude(is_done=True)

#     @property
#     def unseen_announcements(self):
#         from communications.models import AnnouncementStatement
#         announcements = self.threads_participated.filter(
#             kind="Announcement",
#             statements__in=AnnouncementStatement.objects.exclude(seen_by=self))
#         if self.status == 'gm':
#             return announcements.filter(participants=self)
#         return announcements

#     @property
#     def unseen_debates(self):
#         from communications.models import DebateStatement
#         debates = self.threads_participated.filter(
#             kind="Debate",
#             statements__in=DebateStatement.objects.exclude(seen_by=self))
#         if self.status != 'gm':
#             return debates.filter(participants=self)
#         return debates

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# from users.models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = "EMAIL"
        self.fields['username'].label = "LOGIN"


class UserImageUpdateForm(forms.Form):
    user_image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_image'].label = "ZMIEŃ AWATAR UŻYTKOWNIKA (wymiary kwadratu!)"


# class ProfileUpdateForm(forms.ModelForm):

#     class Meta:
#         model = Profile
#         fields = ['image']

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['image'].label = "AWATAR POSTACI (wymiary kwadratu!)"

users/views.py
import random

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.db.models.functions import Length
from django.shortcuts import redirect, render

# from prosoponomikon.forms import CharacterForm
# from prosoponomikon.models import Character, FirstName
from users.forms import UserRegistrationForm, UserUpdateForm, UserImageUpdateForm
# from users.models import Profile


class CustomLoginView(LoginView):
    extra_context = {'page_title': 'Logowanie'}
    template_name = 'users/login.html'
    # settings.py
    # LOGIN_REDIRECT_URL = 'users:home'
    # LOGIN_URL = 'users:login'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)

        self.request.session['character_id'] = user.characters.order_by('-_createdat').first().id
        return HttpResponseRedirect(self.get_success_url())

    # def get(self, request, *args, **kwargs):
    #     """Override method to handle situation when 'go back' browser button is
    #     used from the home page directly after loging in.
    #     Going back from home page would result in NoReverseMatch exception
    #     as request has no 'current_profile' attribute and some navbar & sidebar
    #     links demand it to resolve URLs.
    #     """
    #     hosts = settings.ALLOWED_HOSTS
    #     if any(host in request.META.get('HTTP_REFERER', '') for host in hosts):
    #         logout(request)
    #         redirect('users:login')
    #     return self.render_to_response(self.get_context_data())


class CustomLogoutView(LogoutView):
    # settings.py
    # LOGOUT_REDIRECT_URL = 'users:login'
    pass


def register_view(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        # profile = Profile.objects.create(user=user)
        # Character.objects.create(
        #     profile=profile,
        #     first_name=FirstName.objects.create(
        #         form=user.username.replace('_', ' '))
        # )
        messages.info(
            request, f'Utworzono konto dla {user.username}! Zaloguj się!')
        return redirect('users:login')

    context = {
        'page_title': 'Utwórz profil',
        'form': form
    }
    return render(request, 'users/register.html', context)


@login_required
# @auth_profile(['all'])
def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.info(request, 'Hasło zostało zaktualizowane!')
            return redirect('users:edit-profile')
        else:
            messages.warning(request, 'Popraw poniższy błąd!')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'page_title': 'Zmiana hasła',
        'form': form
    }
    return render(request, 'users/change_password.html', context)


@login_required
# @auth_profile(['all'])
def edit_user_view(request):
    # current_profile = request.current_profile
    # user_profiles = current_profile.user.profiles.all()

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        user_image_form = UserImageUpdateForm(request.POST, request.FILES)

        if user_form.is_valid() and user_image_form.is_valid():
            user_form.save()
            user_image = user_image_form.cleaned_data.get('user_image')
            # if user_image:
            #     for profile in user_profiles:
            #         profile.user_image = user_image
            #         profile.save()

            messages.info(request, 'Zaktualizowano Użytkownika!')
            return redirect('users:edit-user')
    else:
        user_form = UserUpdateForm(instance=request.user)
        user_image_form = UserImageUpdateForm()

    context = {
        'page_title': 'Konto Użytkownika',
        'user_form': user_form,
        'user_image_form': user_image_form,
    }
    return render(request, 'users/edit_user.html', context)


# @login_required
# @auth_profile(['all'])
# def edit_profile_view(request):
#     current_profile = request.current_profile

#     if request.method == 'POST':
#         profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=current_profile)
#         character_form = CharacterForm(request.POST, instance=current_profile.character)
#         if profile_form.is_valid() and character_form.is_valid():
#             profile_form.save()
#             character_form.save()
#             messages.info(request, 'Zaktualizowano Postać!')
#             return redirect('users:edit-profile')
#     else:
#         profile_form = ProfileUpdateForm(instance=current_profile)
#         character_form = CharacterForm(instance=current_profile.character)

#     context = {
#         'page_title': 'Edycja Postaci',
#         'profile_form': profile_form,
#         'character_form': character_form,
#     }
#     return render(request, 'users/edit_profile.html', context)


# @login_required
# @auth_profile(['all'])
# def switch_profile(request, profile_id):
#     request.session['profile_id'] = profile_id
#     chosen_profile = Profile.objects.get(id=profile_id)

#     msg = f"Zmieniono Postać na {chosen_profile.character.fullname}!"
#     messages.info(request, msg)

#     response = redirect(request.META.get('HTTP_REFERER'))
#     if '/dupa/' in response['Location']:
#         msg = """
#             Przekierowano do strony startowej!
#             (Wybrana Postać nie ma dostępu do poprzedniej treści)"""
#         messages.warning(request, msg)
#         return redirect('users:home')

#     return response


# # =============================================================================


# def get_profile(user):
#     """Get User's Profile by the priority of 'status' and probable recent use."""
#     profiles = user.profiles.order_by(
#         'status', '-is_alive', '-is_active', 'character__fullname')
#     return profiles.first()


# def game_event_with_caption(game_events_qs):
#     """Get the beginning (first n words as per words_limit) of a random
#     paragraph from a random GameEvent.description_long from queryset.
#     The paragraph has to have a minimum number of words as per words_min.
#     """
#     if len(game_events_qs) == 0:
#         return None

#     words_min = 40
#     words_limit = 70
#     game_event = sample_from_qs(qs=game_events_qs, max_size=1)[0]

#     paragraphs = game_event.description_long.split('\n')
#     paragraphs = [p for p in paragraphs if len(p.split(' ')) >= words_min]
#     if not paragraphs:
#         return game_event_with_caption(game_events_qs)

#     paragraph = random.choice(paragraphs)
#     caption = paragraph.strip().split(' ')[:words_limit]
#     caption = " ".join(caption).strip().rstrip(";,:.")
#     caption = caption if caption[-1] in ["!", "?", "..."] else caption + "..."
#     game_event.caption = caption

#     return game_event


@login_required
# @auth_profile(['all'])
def home_view(request):
    # current_profile = request.current_profile

    # from imaginarion.models import PictureImage
    # first = PictureImage.objects.first()
    # print(first.image.url)  # /media/post_pics/knowledge_Struktura%20organizacyjna%20Szarej%20Gwardii.jpg
    # print(first.image.path) # C:\Users\Lukasz\PycharmProjects\rpg_hub\media\post_pics\knowledge_Struktura organizacyjna Szarej Gwardii.jpg

    # rand_acquaintanceships = sample_from_qs(
    #     qs=current_profile.character.acquaintanceships().filter(is_direct=True).distinct(),
    #     max_size=4)
    # rand_locations = sample_from_qs(
    #     qs=current_profile.locations_known_annotated().filter(only_indirectly=0).distinct(),
    #     max_size=2)
    # rand_gameevent = game_event_with_caption(
    #     game_events_qs=current_profile.gameevents_known_annotated.filter(
    #         only_indirectly=0
    #     ).annotate(
    #         text_len=Length('description_long')
    #     ).filter(
    #         text_len__gt=400
    #     ).distinct()
    # )

    context = {
        'page_title': 'Hyllemath',
        # 'rand_acquaintanceships': rand_acquaintanceships,
        # 'rand_locations': rand_locations,
        # 'rand_gameevent': rand_gameevent,
    }
    return render(request, 'users/home.html', context)


# @login_required
# @auth_profile(['all'])
# def dupa_view(request):
#     context = {
#         'page_title': 'Dupa',
#     }
#     return render(request, 'users/dupa.html', context)

users/templates/users/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock head_extra %}

{% block content %}
<br><br><br>
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <b>{{ form|crispy }}</b>
    <div class="form-group">
      <button class="btn btn-dark" type="submit">Zapisz</button>
    </div>
  </form>
</div>
{% endblock content %}

users/templates/users/dupa.html
{% extends 'base.html' %}

{% block content %}
  <br><br><br><br>
  <p>Trafiłeś do dupy.</p>
  <p>Jest to miejsce, do którego prędzej czy później dogrzebują się ludzie, którzy dużo grzebią i niekoniecznie tam gdzie trzeba. Generalnie - jest tu pusto i nudno.</p>
  <p>No i niesmak pozostaje...</p>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock head_extra %}

{% block content %}
<br><br><br>
<div class="content-section">
  <div class="media">
    <img class="account-img-profile" src="{{ request.current_profile.image.url }}">
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ character_form|crispy }}
      {{ profile_form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-dark" type="submit">Zapisz</button>
    </div>
  </form>
</div>
{% endblock content %}

users/templates/users/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock head_extra %}

{% block content %}
<br><br><br>
<div class="content-section">
  <div class="media">
    <img class="account-img-profile" src="{{ request.current_profile.user_img_url }}">
    <div class="media-body">
      <div class="account-heading h4 d-flex justify-content-between">
        <div>
          {{ user.username }}
          <small class="text-secondary d-block smaller">{{ user.email }}</small>
        </div>
        <div class="float-right">
          <a href="{% url 'users:change-password' %}" class="btn btn-outline-dark float-right mb-1 mr-1">Zmiana
            hasła</a>
        </div>
      </div>
    </div>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ user_form|crispy }}
      {{ user_image_form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-dark" type="submit">Zapisz</button>
    </div>
  </form>
</div>
{% endblock content %}

users/templates/users/home.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}

<article>

  <!--   Beginning of a random paragraph from a random GameEvent    -->
  {% if rand_gameevent %}
  <section>
    <div class="container px-3 pb-3 mb-4">
      <div class="row">
        <a href="{% url 'chronicles:chronicle-game' rand_gameevent.game.id %}#event_{{ rand_gameevent.id }}">
          <p class="font-18 font-italic px-2 pb-0 mt-3 mb-0 text-justify content-section border-none fading-top-bottom
              {% if request.current_profile not in event.participants.all and request.current_profile.status != 'gm' %} text-muted {% endif %}"
            data-toggle="tooltip" data-placement="bottom" data-html="true"
            title='<span class="font-italic">Pokaż Kronikę wydarzenia</span>'>
            {{ rand_gameevent.caption }}
          </p>
        </a>
      </div>
    </div>
  </section>
  {% endif %}

  <!--   Random pictures from Prosoponomikon    -->
  <section>
    <div class="container px-2 pb-3 mb-4">
      <div class="row">
        {% for acquaintanceship in rand_acquaintanceships %}
          {% with show_caption=False %}
            {% include 'prosoponomikon/_acquaintance_img.html' %}
          {% endwith %}
        {% endfor %}
      </div>
    </div>
  </section>

  <!--   Random pictures from Toponomikon    -->
  <section>
    <div class="container px-2 pb-3 mb-4">
      <div class="row">
        {% for location in rand_locations %}
        <div class="col-sm-12 col-lg-6 px-2">
          {% with show_caption=False %}
            {% include 'toponomikon/_loc_img.html' %}
          {% endwith %}
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <!--   Random pictures from Therarion    -->
  <section>
    <div class="container px-2">
      <div class="row">

      </div>
    </div>
  </section>

</article>

{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock head_extra %}

{% block content %}
<br><br><br>
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <b>{{ form|crispy }}</b>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-dark" type="submit">Zaloguj</button>
    </div>
  </form>
  <div class="border-top pt-3">
    <small>
      Twoja Postać poległa?
      <a class="ml-2" href="{% url 'users:register' %}">Nowa Postać</a>
    </small>
  </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock head_extra %}

{% block content %}
<br><br><br>
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <b>{{ form|crispy }}</b>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-dark" type="submit">Utwórz</button>
    </div>
  </form>
  <div class="border-top pt-3">
    <small>
      Twoja Postać nadal trzyma się przy życiu?
      <a class="ml-2" href="{% url 'users:login' %}">Logowanie</a>
    </small>
  </div>
</div>
{% endblock content %}